

                     expression  ::=  stringExpression ;


               stringExpression  ::=  "(" stringExpression ")"

                                   |  type "+" type

                                   |  type<NO_WHITESPACE>( ( "[" "..." type "]" ) 

                                                         | ( "[" type "..." type "]"  ) 

                                                         | ( "[" type  "..." "]" ) 
      
                                                         )

                                   |  stringExpression "+" stringExpression 

                                   |  stringExpression<NO_WHITESPACE>( ( "[" "..." arithmeticExpression "]" ) 

                                                                     | ( "[" arithmeticExpression "..." arithmeticExpression "]"  ) 

                                                                     | ( "[" arithmeticExpression "..." "]" ) 
      
                                                                     )

                                   |  stringTerm 

                                   ; 

