

                   stringExpression  ::=  "(" stringExpression ")"

                                       |  stringExpression "+" stringExpression 

                                       |  stringTerm 

                                       |  [name]
                       
                                       ; 

