

                   stringExpression  ::=  "(" stringExpression ")"

                                       |  stringExpression "+" stringExpression 

                                       |  stringTerm 

                                       |  typeName 
                       
                                       ;   

