

                         statement  ::=  type ( "<" | "<=" | ">=" | ">" ) type 

                                      |  stringExpression ( "<" | "<=" | ">=" | ">" ) stringExpression

                                      ;


