

                       term  ::=  argument<NO_WHITESPACE>( ( "[" "..." argument "]" ) 

                                                         | ( "[" argument "..." argument "]"  ) 

                                                         | ( "[" argument  "..." "]" ) 
      
                                                         )

                               |  argument "+" argument 

                               |  "|" argument "|" 

                               |  [string-literal] 

                               ; 

