

                       term  ::=  name<NO_WHITESPACE>( ( "[" "..." expression "]" ) 

                                                     | ( "[" expression "..." expression "]"  ) 

                                                     | ( "[" expression "..."  "]" ) 

                                                     )

                               |  "|" term "|"

                               ;
