

                       term  ::=  stringTerm ;


                 stringTerm  ::=  argument<NO_WHITESPACE>( ( "[" "..." argument "]" ) 

                                                         | ( "[" argument "..." argument "]"  ) 

                                                         | ( "[" argument  "..." "]" ) 
      
                                                         )

                               |  argument "+" argument 

                               |  [string-literal] 

                               ; 


              naturalNumber  ::=  "|" argument "|" ;

